version: "3"

services:
  frontend:
    container_name: next-dev
    image: next-dev:tea42
    build:
      context: service/frontend/
      dockerfile: Dockerfile
    volumes:
      - front_repo:/usr/app/srcs
    networks:
      - tea42_network
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: always

volumes:
  front_repo:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/frontend"

networks:
  tea42_network:
    driver: bridge
